frame.png: logic-capture-actually-a-txt-file.doc gb-logic-decoder.py
	./gb-logic-decoder.py

logic-capture-actually-a-txt-file.doc:
	wget http://flashingleds.files.wordpress.com/2010/09/logic-capture-actually-a-txt-file.doc
